version: 2
jobs:
  build:
    docker:
      - image: tm604/perl-docker
        entrypoint: /bin/bash
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            cpanm --installdeps -n .
      - run:
          name: Run test
          command: |
            prove -vmlr t/
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
