version: 2
jobs:
  build:
    docker:
      - image: deriv/dzil
        entrypoint: /bin/bash
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            cpanm --installdeps -n .
      - run:
          name: Run test
          command: |
            dzil test
      - run:
          name: Author tests
          command: |
            dzil xtest
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
