version: 2
jobs:
  build:
    docker:
      - image: deriv/dzil:latest
        entrypoint: /bin/bash
    steps:
      - checkout
      - restore_cache:
          keys:
            - cpanfile-{{ arch }}-{{ checksum "cpanfile" }}
      - run:
          name: Install deps
          command: |
            cpanm -l deps --installdeps -n .
      - save_cache:
          key: cpanfile-{{ arch }}-{{ checksum "cpanfile" }}
          paths:
            - deps
      - run:
          name: Run test
          command: |
            # Upstream Pod::Inherit is no longer maintained, we may end up needing
            # to fork this but for now we can patch it out...
            perl -i -lpe's{did_it = \$src \? do \K\$src}{"./\$src"}' $(perldoc -lm Pod::Inherit)
            dzil test
      - run:
          name: Author tests
          command: |
            dzil xtest
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
